spring:
  application:
    name: soccer-shirt-ecommerce

server:
  port: 8080

logging:
  level:
    com.soccershirt: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"