logging:
  level:
    com.soccershirt: INFO
    org.springframework.web: WARN
    root: WARN

spring:
  jpa:
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
