export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN';
export const SESSION_SERVICE_TOKEN = 'SESSION_SERVICE_TOKEN';
export const CPF_VALIDATOR_TOKEN = 'CPF_VALIDATOR_TOKEN';
export const EMAIL_VALIDATOR_TOKEN = 'EMAIL_VALIDATOR_TOKEN';
